version: '3.3'

services: 
  
  docker-test:
    image: docker-test
    container_name: docker-test
    build:
      #the builds context is the set of files at a specified location
      #it is basically saying HEY look for my dockerfile at the base of the application
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'